"""Public runtime substrate for BioBank-Agent 2.0."""

from biobank_agent.core.events import AgentEvent, AgentEventType

from .audit import RuntimeAuditReport, audit_session, write_audit_report
from .engine import AgentRuntime, AgentSession, FakeProvider, ProviderRouter, SessionStore
from .evolution import EvolutionProposal, LearningReport, collect_feedback, learn_from_session, propose_improvements, reject_persistent_apply, write_learning_report
from .harness import HARNESS_SCHEMA_VERSION, HarnessExpectations, HarnessRunReport, HarnessStep, HarnessTask, RuntimeHarnessRunner, StaticHarnessTool, write_harness_report
from .hooks import HookOutcome, HookRegistry, default_registry, emit_hook, hook, make_command_hook
from .patch_generation import (
    PatchGenerationResult,
    enrich_proposals_with_patches,
    generate_and_apply_proposals,
    generate_patch_for_proposal,
)
from .replay import ReplayReport, replay_trajectory
from .self_evolve import DEFAULT_APPLY_ALLOW_PATHS, EvolutionApplyResult, apply_patch_transactionally, apply_proposal
from .types import (
    ActionGraphNode,
    ApprovalRequest,
    AssistantMessage,
    GoalState,
    GoalStatus,
    PlanState,
    PlanStatus,
    PlanStep,
    ProviderRequest,
    ProviderResponse,
    ProviderRole,
    RuntimeCheckpoint,
    RuntimeConfig,
    RuntimeState,
    RuntimeStatus,
    StreamEvent,
    ToolCall,
    ToolResult,
    VerificationResult,
    TrajectoryRecord,
    UserTurn,
)

__all__ = [
    "AgentEvent",
    "AgentEventType",
    "AgentRuntime",
    "AgentSession",
    "FakeProvider",
    "HookOutcome",
    "HookRegistry",
    "default_registry",
    "emit_hook",
    "hook",
    "make_command_hook",
    "HARNESS_SCHEMA_VERSION",
    "HarnessExpectations",
    "HarnessRunReport",
    "HarnessStep",
    "HarnessTask",
    "ProviderRouter",
    "SessionStore",
    "ActionGraphNode",
    "ApprovalRequest",
    "AssistantMessage",
    "DEFAULT_APPLY_ALLOW_PATHS",
    "EvolutionApplyResult",
    "EvolutionProposal",
    "PatchGenerationResult",
    "GoalState",
    "GoalStatus",
    "LearningReport",
    "PlanState",
    "PlanStatus",
    "PlanStep",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderRole",
    "RuntimeCheckpoint",
    "RuntimeConfig",
    "RuntimeAuditReport",
    "RuntimeHarnessRunner",
    "RuntimeState",
    "RuntimeStatus",
    "ReplayReport",
    "StreamEvent",
    "ToolCall",
    "ToolResult",
    "VerificationResult",
    "TrajectoryRecord",
    "UserTurn",
    "apply_patch_transactionally",
    "apply_proposal",
    "audit_session",
    "collect_feedback",
    "enrich_proposals_with_patches",
    "generate_and_apply_proposals",
    "generate_patch_for_proposal",
    "learn_from_session",
    "propose_improvements",
    "reject_persistent_apply",
    "replay_trajectory",
    "StaticHarnessTool",
    "write_audit_report",
    "write_harness_report",
    "write_learning_report",
]
