"""Report section templates and styling for Biobank Agent.

Provides:
- Markdown templates for technical reports and paper drafts
- CSS for Nature-style HTML rendering
- LaTeX preamble for PDF generation
- Figure caption templates
"""

# ── Technical Report Template ────────────────────────────────

REPORT_HEADER = """\
# {title}

**Date:** {date}
**Generated by:** Biobank Agent v2.0
**Format:** {format_name}

---

"""

KEY_FINDINGS_BOX = """\
> **Key Findings**
>
{findings}

---

"""

EXECUTIVE_SUMMARY = """\
## Executive Summary

{summary}

"""

SECTION_HEADER = "## {n}. {title}\n\n"

FIGURE_CAPTION = """\
**Figure {n}.** {description}. {stats}

"""

TABLE_CAPTION = "**Table {n}.** {description}\n\n"

# ── Paper Draft Template (IMRaD) ─────────────────────────────

PAPER_TITLE = "# {title}\n\n"

PAPER_AUTHORS = "{authors}\n\n"

PAPER_ABSTRACT = """\
## Abstract

{abstract}

**Keywords:** {keywords}

---

"""

PAPER_INTRODUCTION = """\
## Introduction

{introduction}

"""

PAPER_METHODS = """\
## Methods

### Study Population

{study_population}

### Statistical Analysis

{statistical_analysis}

"""

PAPER_RESULTS = """\
## Results

{results}

"""

PAPER_DISCUSSION = """\
## Discussion

{discussion}

### Limitations

{limitations}

### Conclusions

{conclusions}

"""

# ── Figure and Analysis Interpretation Templates ─────────────

PREVALENCE_INTERPRETATION = (
    "The prevalence analysis identified {n_diseases} disease codes in the UK Biobank cohort "
    "(N={n_subjects:,}). The most prevalent condition was {top_disease} ({top_code}), "
    "affecting {top_count:,} participants ({top_pct:.1f}% of the cohort). "
    "{additional_context}"
)

COHORT_INTERPRETATION = (
    "The {disease_name} cohort comprised {n_cases:,} cases and {n_controls:,} matched controls "
    "(total N={n_total:,}). Cases had a mean age of {mean_age_cases:.1f} years "
    "({pct_female_cases:.1f}% female), compared to {mean_age_controls:.1f} years "
    "({pct_female_controls:.1f}% female) in controls. "
    "{additional_context}"
)

MODEL_INTERPRETATION = (
    "The {model_type} classifier achieved an AUC of {auc:.4f} "
    "(95% CI: {ci_lower:.4f}-{ci_upper:.4f}) using {n_features} features "
    "on the {disease_name} prediction task. "
    "The model was trained on {n_train:,} samples and evaluated on {n_test:,} held-out samples "
    "using {n_folds}-fold cross-validation. "
    "{additional_context}"
)

BIOMARKER_INTERPRETATION = (
    "Comparison of {biomarker_name} between cases and controls revealed "
    "a {direction} in cases (median: {median_cases:.2f} vs {median_controls:.2f}, "
    "P={p_value:.2e}, Mann-Whitney U test). "
    "The effect size (Cohen's d) was {cohens_d:.2f}, indicating a {effect_magnitude} effect. "
    "{additional_context}"
)

SURVIVAL_INTERPRETATION = (
    "Kaplan-Meier analysis of {disease_name} ({icd10_code}) showed a median survival of "
    "{median_survival} years from first diagnosis. "
    "The 5-year survival rate was {five_yr_rate:.1f}% and 10-year rate was {ten_yr_rate:.1f}%. "
    "Log-rank test: {log_rank_result}. "
    "{additional_context}"
)

FEATURE_IMPORTANCE_INTERPRETATION = (
    "Feature importance analysis identified {top_feature} as the most predictive biomarker "
    "for {disease_name} (SHAP value: {top_shap:.4f}). "
    "The top 5 features were: {top_5_list}. "
    "These features collectively explain {cumulative_importance:.1f}% of model predictions. "
    "{additional_context}"
)

# ── CSS for HTML Reports ─────────────────────────────────────

NATURE_CSS = """\
<style>
    body {
        font-family: 'Helvetica Neue', Arial, sans-serif;
        font-size: 10pt;
        line-height: 1.6;
        max-width: 900px;
        margin: 0 auto;
        padding: 40px 20px;
        color: #333;
    }
    h1 {
        font-size: 18pt;
        font-weight: 700;
        border-bottom: 2px solid #0072B2;
        padding-bottom: 8px;
        margin-bottom: 24px;
    }
    h2 {
        font-size: 14pt;
        font-weight: 600;
        color: #0072B2;
        margin-top: 32px;
        margin-bottom: 12px;
    }
    h3 {
        font-size: 11pt;
        font-weight: 600;
        margin-top: 20px;
    }
    blockquote {
        background: #f0f7fc;
        border-left: 4px solid #0072B2;
        padding: 12px 16px;
        margin: 16px 0;
        font-size: 10pt;
    }
    table {
        border-collapse: collapse;
        width: 100%;
        margin: 16px 0;
        font-size: 9pt;
    }
    th {
        background: #f5f5f5;
        border-bottom: 2px solid #333;
        padding: 8px 12px;
        text-align: left;
        font-weight: 600;
    }
    td {
        border-bottom: 1px solid #ddd;
        padding: 6px 12px;
    }
    img {
        max-width: 100%;
        display: block;
        margin: 16px auto;
    }
    .figure-caption {
        font-size: 9pt;
        color: #666;
        text-align: center;
        margin-top: -8px;
        margin-bottom: 24px;
    }
    code {
        background: #f5f5f5;
        padding: 2px 6px;
        border-radius: 3px;
        font-size: 9pt;
    }
    .key-findings {
        background: #e8f4e8;
        border-left: 4px solid #009E73;
        padding: 12px 16px;
        margin: 16px 0;
    }
    @media (prefers-color-scheme: dark) {
        body { background: #1a1a1a; color: #e0e0e0; }
        h1, h2 { color: #56B4E9; border-color: #56B4E9; }
        blockquote { background: #2a2a2a; border-color: #56B4E9; }
        th { background: #2a2a2a; border-color: #e0e0e0; }
        td { border-color: #444; }
        code { background: #2a2a2a; }
        .key-findings { background: #1a2a1a; }
    }
</style>
"""

# ── LaTeX Preamble for PDF Generation ────────────────────────

LATEX_PREAMBLE = r"""\
\documentclass[10pt,a4paper]{article}
\usepackage[margin=2.5cm]{geometry}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{xcolor}
\definecolor{linkblue}{RGB}{0,114,178}
\usepackage[colorlinks=true,linkcolor=linkblue,urlcolor=linkblue]{hyperref}
\usepackage{float}
\usepackage{caption}
\captionsetup{font=small,labelfont=bf}
"""
