"""Report generator — compile all figures and results into markdown + HTML."""

from pathlib import Path
from datetime import datetime

from biobank_agent.registry import skill


@skill(
    name="generate_report",
    description="Generate a structured analysis report from all analyses performed in this session. "
                "Compiles figures, metrics, and interpretations into markdown and HTML.",
    parameters={
        "title": {
            "type": "string",
            "description": "Report title",
            "default": "UK Biobank Analysis Report",
        },
    },
    required=[],
)
def generate_report(title: str = "UK Biobank Analysis Report", *, ctx=None) -> dict:
    report_dir = ctx.report_dir
    report_dir.mkdir(parents=True, exist_ok=True)

    sections = []
    sections.append(f"# {title}\n")
    sections.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
    sections.append(f"**Generated by:** Biobank Agent v0.1.0\n")
    sections.append("---\n")

    # Compile analysis records
    if ctx.state.records:
        sections.append("## Analysis Summary\n")
        for i, rec in enumerate(ctx.state.records, 1):
            if rec.skill == "think":
                continue
            sections.append(f"### {i}. {rec.skill}\n")
            if rec.args:
                args_str = ", ".join(f"`{k}={v}`" for k, v in rec.args.items())
                sections.append(f"**Parameters:** {args_str}\n")
            if rec.key_results:
                sections.append("**Results:**\n")
                for k, v in rec.key_results.items():
                    if k == "error":
                        sections.append(f"- ⚠ Error: {v}\n")
                    elif k == "figure":
                        continue  # handled below
                    elif isinstance(v, list) and len(v) > 5:
                        sections.append(f"- {k}: [{v[0]}, ..., {v[-1]}] ({len(v)} items)\n")
                    else:
                        sections.append(f"- {k}: {v}\n")
            sections.append("")

    # Figures section
    if ctx.state.figures:
        sections.append("## Figures\n")
        for fig_path in ctx.state.figures:
            p = Path(fig_path)
            if p.suffix == ".png":
                rel = p.name
                sections.append(f"![{p.stem}]({rel})\n")
        sections.append("")

    # Cohort info
    if ctx.state.cohorts:
        sections.append("## Cohorts\n")
        for name, df in ctx.state.cohorts.items():
            n_cases = int(df["label"].sum()) if "label" in df.columns else "N/A"
            sections.append(f"- **{name}**: {len(df)} subjects ({n_cases} cases)\n")

    # Model info
    if ctx.state.model_metadata:
        sections.append("## Models\n")
        sections.append("| Key | Type | AUC | Cases | Features |\n")
        sections.append("|-----|------|-----|-------|----------|\n")
        for key, meta in ctx.state.model_metadata.items():
            sections.append(
                f"| {key} | {meta.get('model_type', '?')} | "
                f"{meta.get('auc', '?'):.4f} | {meta.get('n_cases', '?')} | "
                f"{meta.get('n_features', '?')} |\n"
            )

    # Write markdown
    md_content = "\n".join(sections)
    md_path = report_dir / "report.md"
    md_path.write_text(md_content)

    # Try HTML conversion
    html_path = report_dir / "report.html"
    try:
        import subprocess
        result = subprocess.run(
            ["pandoc", str(md_path), "-o", str(html_path),
             "--self-contained", "--toc", "--highlight-style=tango",
             f"--metadata=title:{title}"],
            capture_output=True, timeout=30,
        )
        if result.returncode != 0:
            html_path = None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        html_path = None

    return {
        "report_dir": str(report_dir),
        "markdown": str(md_path),
        "html": str(html_path) if html_path else None,
        "n_sections": len(ctx.state.records),
        "n_figures": len(ctx.state.figures),
    }
